In [2]:
import pandas as pd
import numpy as np
import datetime as dt

In [3]:
rd = pd.read_csv('online_retail.csv', encoding='utf-8-sig')

In [4]:
print(rd.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [20]:
rd.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/2010 08:26,3.39,17850.0,United Kingdom

In [5]:
# Clean column names
rd.columns = rd.columns.str.strip()

In [6]:
print(rd.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [7]:
print("DataFrame columns:", rd.columns.tolist())

DataFrame columns: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

In [11]:
# Convert datetime in the correct format
rd['InvoiceDate'] = pd.to_datetime(rd['InvoiceDate'], dayfirst=True)
#rd['InvoiceDate'] = rd['InvoiceDate'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [12]:
rd.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART TLIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [13]:
# Get the date range
min_date = rd['InvoiceDate'].min()
max_date = rd['InvoiceDate'].max()
date_range = max_date - min_date
    
print(f"Start date: {min_date}")
print(f"End date: {max_date}")
print(f"Date range: {date_range}")
print(f"Total days: {date_range.days}")

Start date: 2010-12-01 08:26:00
End date: 2011-12-09 12:50:00
Date range: 373 days 04:24:00
Total days: 373

In [28]:
# Getting the basic statistics of the numerical columns of the dataset
rd.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [14]:
#Checking for missing values
rd.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [10]:
# We found in Excel that the Description column includes many characters like ?, we need to remove these characters
#rd['Description'] = rd['Description'].str.replace(r'[^\w\s]', '', regex=True)

In [31]:
# Now we need to check for missing values again
rd.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [15]:
# We will now remove the misssing values 
rd = rd.dropna(subset=['CustomerID', 'Description'])

In [16]:
rd.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [17]:
# Saving the cleaned data
rd.to_csv("clean_retail.csv", index=False)

In [18]:
from sqlalchemy import create_engine

# Load cleaned file
df = pd.read_csv("clean_retail.csv")

# Connect to MySQL
engine = create_engine("mysql+pymysql://root:DamnDan%40%4099@localhost/retail_project")

# Upload to MySQL
df.to_sql('retail', con=engine, if_exists='replace', index=False, chunksize=10000)

406829

In [19]:
engine.connect()
#upload successful